apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitea-runner-operator.fullname" . }}-metrics-service
  labels:
    control-plane: controller-manager
    {{- include "gitea-runner-operator.labels" . | nindent 4 }}
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: {{ .Values.manager.metricsBindAddress | trimPrefix ":" }}
  selector:
    {{- include "gitea-runner-operator.selectorLabels" . | nindent 4 }}
