# This rule is not used by the project gitea-runner-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to gitea.bpg.pw resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gitea-runner-operator
    app.kubernetes.io/managed-by: kustomize
  name: runnergroup-viewer-role
rules:
- apiGroups:
  - gitea.bpg.pw
  resources:
  - runnergroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gitea.bpg.pw
  resources:
  - runnergroups/status
  verbs:
  - get
