# This rule is not used by the project gitea-runner-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over gitea.bpg.pw.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gitea-runner-operator
    app.kubernetes.io/managed-by: kustomize
  name: runnergroup-admin-role
rules:
- apiGroups:
  - gitea.bpg.pw
  resources:
  - runnergroups
  verbs:
  - '*'
- apiGroups:
  - gitea.bpg.pw
  resources:
  - runnergroups/status
  verbs:
  - get
